import { Lesson } from "./types";

export const LESSONS: Lesson[] = [
  // --- 基本の駒の動き ---
  { id: "pawn", title: "基本の駒の動き（歩）", description: "まずは歩の動きを覚えましょう。将棋の基本となる駒です。", category: "basics", status: "available", order: 1 },
  { id: "lance", title: "基本の駒の動き（香車）", description: "前にどこまでも進める「槍」のような駒です。バックはできません。", category: "basics", status: "available", order: 2 },
  { id: "knight", title: "基本の駒の動き（桂馬）", description: "唯一、駒を飛び越えられるトリッキーな駒です。", category: "basics", status: "available", order: 3 },
  { id: "silver", title: "基本の駒の動き（銀）", description: "攻めの要となる駒。斜め後ろに下がれるのがポイントです。", category: "basics", status: "available", order: 4 },
  { id: "gold", title: "基本の駒の動き（金）", description: "守りの要。斜め後ろ以外、すべての方向に進めます。", category: "basics", status: "available", order: 5 },
  { id: "bishop", title: "基本の駒の動き（角）", description: "斜めにどこまでも進めます。成ると「馬」になります。", category: "basics", status: "available", order: 6 },
  { id: "rook", title: "基本の駒の動き（飛車）", description: "縦横にどこまでも進めます。成ると最強の「龍」に。", category: "basics", status: "available", order: 7 },
  { id: "king", title: "基本の駒の動き（王）", description: "取られたら負け。全方向に1マスずつ動けます。", category: "basics", status: "available", order: 8 },

  // --- 詰将棋 ---
  
  // 1手詰 (基本)
  {
    // ★ここを変更！ "001" ではなく "tsume1-001" にします
    id: "tsume1-001", 
    title: "1手詰：第1問",
    description: "王手をかけて相手の玉を詰ませる「詰将棋」の基本です。",
    category: "tsume-1",
    status: "available",
    order: 9,
  },

  // 1手詰 (中盤・連携)
  {
    // ★ここも変更！ "001" ではなく "tsume2-001" にします
    id: "tsume2-001",
    title: "1手詰・中盤：第1問",
    description: "盤上の駒を連携させて詰ませる練習です。",
    category: "tsume-2",
    status: "available",
    order: 10,
  },

  {
    // ★ここも変更！ "001" ではなく "tsume2-001" にします
    id: "tsume3-001",
    title: "1手詰・中盤：第1問",
    description: "盤上の駒を連携させて詰ませる練習です。",
    category: "tsume-3",
    status: "available",
    order: 11,
  },

  // --- ミニゲーム: 浮き駒キャプチャ ---
  {
    id: "uki-capture",
    title: "駒の効き：浮き駒を取る（60秒）",
    description: "浮き駒（守られていない駒）を素早く見つけて取る60秒タイムアタック。",
    category: "basics",
    status: "available",
    order: 999,
    stars: 1,
    href: "/training/uki-capture",
  },

  {
    id: "basics_pawn_0",
    title: "歩の動きと成り（復習）",
    description: "歩は前に1マス。敵陣で成る/不成、成りのタイミングを確認します。",
    category: "basics",
    status: "available",
    order: 12,
    href: "/training/basics/pawn",
    stars: 0,
    prerequisites: [],
  },

  {
    id: "basics_pawn_0_remake",
    title: "歩の動きと成り_作り直し",
    description: "歩は前に1マス。敵陣で成る/不成、成りのタイミングを確認します。（Duolingo風UI）",
    category: "basics",
    status: "available",
    order: 13,
    href: "/training/basics/pawn",
    stars: 0,
    prerequisites: [],
  },

  {
    id: "basics_pawn_1_role",
    title: "歩の役割（壁・道を開ける・捨て駒・と金）",
    description:
      "歩は守りでは壁、攻めでは道を開ける。歩交換や捨て歩、と金の強さまで体験します。",
    category: "basics",
    status: "available",
    order: 2,
    href: "/training/basics/pawn/role",
    stars: 0,
    prerequisites: ["basics_pawn_0"],
  },

  {
    id: "basics_pawn_2_tarefu",
    title: "垂れ歩",
    description: "相手の1つ手前に歩を打ち、『次に成る』プレッシャーを作る手筋を体験します。",
    category: "basics",
    status: "available",
    order: 3,
    href: "/training/basics/pawn/tarefu",
    stars: 0,
    prerequisites: ["basics_pawn_1_role"],
  },

  {
    id: "basics_pawn_3_tsugifu",
    title: "継ぎ歩",
    description: "歩を取らせたあと、持ち歩を同じ筋に継いで圧力を続ける手筋を体験します。",
    category: "basics",
    status: "available",
    order: 4,
    href: "/training/basics/pawn/tsugifu",
    stars: 0,
    prerequisites: ["basics_pawn_2_tarefu"],
  },

  // --- 手筋（テスト接続：Lv1） ---
  // 継ぎ歩の次に“歩の手筋4つ”を並べる（最小差分）
  {
    id: "tesuji_pawn_tataki_l1",
    title: "叩きの歩（Lv1）",
    description: "歩を叩いて反応を引き出し、狙いを通す形を覚えます。",
    category: "basics",
    status: "available",
    order: 5,
    href: "/training/tesuji/pawn/tataki",
    stars: 0,
    prerequisites: ["basics_pawn_3_tsugifu"],
  },
  {
    id: "tesuji_pawn_renda_l1",
    title: "歩の連打（Lv1）",
    description: "取られても同じ地点にもう一枚。圧力を続ける形を覚えます。",
    category: "basics",
    status: "available",
    order: 6,
    href: "/training/tesuji/pawn/renda",
    stars: 0,
    prerequisites: ["basics_pawn_3_tsugifu"],
  },
  {
    id: "tesuji_pawn_hikae_l1",
    title: "控えの歩（Lv1）",
    description: "いきなり突かず、1つ後ろに歩を置いて土台を作る形を覚えます。",
    category: "basics",
    status: "available",
    order: 7,
    href: "/training/tesuji/pawn/hikae",
    stars: 0,
    prerequisites: ["basics_pawn_3_tsugifu"],
  },
  {
    id: "tesuji_pawn_sokobu_l1",
    title: "底歩（Lv1）",
    description: "玉の近くに歩を打って、飛車や香の筋を止める形を覚えます。",
    category: "basics",
    status: "available",
    order: 8,
    href: "/training/tesuji/pawn/sokobu",
    stars: 0,
    prerequisites: ["basics_pawn_3_tsugifu"],
  },

  // 銀/金の手筋（Lv1）
  {
    id: "tesuji_silver_keitogin_l1",
    title: "桂頭の銀（Lv1）",
    description: "桂の頭に銀を置いて、桂の動きを止める形を覚えます。",
    category: "basics",
    status: "available",
    order: 9,
    href: "/training/tesuji/silver/keitogin",
    stars: 0,
    prerequisites: ["tesuji_pawn_sokobu_l1"],
  },
  {
    id: "tesuji_silver_haragin_l1",
    title: "腹銀（Lv1）",
    description: "玉の斜め下（腹）に銀を置き、逃げ道を絞る形を覚えます。",
    category: "basics",
    status: "available",
    order: 10,
    href: "/training/tesuji/silver/haragin",
    stars: 0,
    prerequisites: ["tesuji_silver_keitogin_l1"],
  },
  {
    id: "tesuji_gold_atamakin_l1",
    title: "頭金（Lv1）",
    description: "玉の前に金を打って、動きを止める形を覚えます。",
    category: "basics",
    status: "available",
    order: 11,
    href: "/training/tesuji/gold/atamakin",
    stars: 0,
    prerequisites: ["tesuji_silver_haragin_l1"],
  },
  {
    id: "tesuji_gold_shirikin_l1",
    title: "尻金（Lv1）",
    description: "玉の後ろに金を打って、退路を断つ形を覚えます。",
    category: "basics",
    status: "available",
    order: 12,
    href: "/training/tesuji/gold/shirikin",
    stars: 0,
    prerequisites: ["tesuji_gold_atamakin_l1"],
  },

  // --- 手筋（Lv1）一括表示：残り（雛形でもOK） ---
  {
    id: "tesuji_pawn_tarefu_l1",
    title: "垂れ歩（Lv1）",
    description: "相手の1つ手前に歩を打つ形（Lv1）。",
    category: "basics",
    status: "available",
    order: 13,
    href: "/training/tesuji/pawn/tarefu",
    stars: 0,
    prerequisites: ["tesuji_gold_shirikin_l1"],
  },
  {
    id: "tesuji_pawn_tsugifu_l1",
    title: "継ぎ歩（Lv1）",
    description: "取らせた地点にもう一枚。継ぐ形（Lv1）。",
    category: "basics",
    status: "available",
    order: 14,
    href: "/training/tesuji/pawn/tsugifu",
    stars: 0,
    prerequisites: ["tesuji_pawn_tarefu_l1"],
  },
  {
    id: "tesuji_silver_warigin_l1",
    title: "割打ちの銀（Lv1）",
    description: "割って入る銀で二枚を見る形（Lv1）。",
    category: "basics",
    status: "available",
    order: 15,
    href: "/training/tesuji/silver/warigin",
    stars: 0,
    prerequisites: ["tesuji_pawn_tsugifu_l1"],
  },

  // lance
  {
    id: "tesuji_lance_dengaku-sashi_l1",
    title: "田楽刺し（Lv1）",
    description: "田楽刺し（Lv1）。",
    category: "basics",
    status: "available",
    order: 16,
    href: "/training/tesuji/lance/dengaku-sashi",
    stars: 0,
    prerequisites: ["tesuji_silver_warigin_l1"],
  },
  {
    id: "tesuji_lance_2dan-rocket_l1",
    title: "2段ロケット（Lv1）",
    description: "2段ロケット（Lv1）。",
    category: "basics",
    status: "available",
    order: 17,
    href: "/training/tesuji/lance/2dan-rocket",
    stars: 0,
    prerequisites: ["tesuji_lance_dengaku-sashi_l1"],
  },
  {
    id: "tesuji_lance_sokokyo_l1",
    title: "底香（Lv1）",
    description: "底香（Lv1）。",
    category: "basics",
    status: "available",
    order: 18,
    href: "/training/tesuji/lance/sokokyo",
    stars: 0,
    prerequisites: ["tesuji_lance_2dan-rocket_l1"],
  },

  // knight
  {
    id: "tesuji_knight_fundoshi-kei_l1",
    title: "ふんどしの桂（Lv1）",
    description: "ふんどしの桂（Lv1）。",
    category: "basics",
    status: "available",
    order: 19,
    href: "/training/tesuji/knight/fundoshi-kei",
    stars: 0,
    prerequisites: ["tesuji_lance_sokokyo_l1"],
  },
  {
    id: "tesuji_knight_futo-no-kei_l1",
    title: "歩頭の桂（Lv1）",
    description: "歩頭の桂（Lv1）。",
    category: "basics",
    status: "available",
    order: 20,
    href: "/training/tesuji/knight/futo-no-kei",
    stars: 0,
    prerequisites: ["tesuji_knight_fundoshi-kei_l1"],
  },
  {
    id: "tesuji_knight_tsurushi-kei_l1",
    title: "つるし桂（Lv1）",
    description: "つるし桂（Lv1）。",
    category: "basics",
    status: "available",
    order: 21,
    href: "/training/tesuji/knight/tsurushi-kei",
    stars: 0,
    prerequisites: ["tesuji_knight_futo-no-kei_l1"],
  },
  {
    id: "tesuji_knight_hikae-kei_l1",
    title: "控えの桂（Lv1）",
    description: "控えの桂（Lv1）。",
    category: "basics",
    status: "available",
    order: 22,
    href: "/training/tesuji/knight/hikae-kei",
    stars: 0,
    prerequisites: ["tesuji_knight_tsurushi-kei_l1"],
  },
  {
    id: "tesuji_knight_tsugikei_l1",
    title: "継ぎ桂（Lv1）",
    description: "継ぎ桂（Lv1）。",
    category: "basics",
    status: "available",
    order: 23,
    href: "/training/tesuji/knight/tsugikei",
    stars: 0,
    prerequisites: ["tesuji_knight_hikae-kei_l1"],
  },

  // bishop
  {
    id: "tesuji_bishop_kaku-ryotori_l1",
    title: "角での両取り（Lv1）",
    description: "角での両取り（Lv1）。",
    category: "basics",
    status: "available",
    order: 24,
    href: "/training/tesuji/bishop/kaku-ryotori",
    stars: 0,
    prerequisites: ["tesuji_knight_tsugikei_l1"],
  },
  {
    id: "tesuji_bishop_suji-chigai_l1",
    title: "筋違いの角打ち（Lv1）",
    description: "筋違いの角打ち（Lv1）。",
    category: "basics",
    status: "available",
    order: 25,
    href: "/training/tesuji/bishop/suji-chigai",
    stars: 0,
    prerequisites: ["tesuji_bishop_kaku-ryotori_l1"],
  },
  {
    id: "tesuji_bishop_kaku-kei_l1",
    title: "角桂連携（Lv1）",
    description: "角桂連携（Lv1）。",
    category: "basics",
    status: "available",
    order: 26,
    href: "/training/tesuji/bishop/kaku-kei",
    stars: 0,
    prerequisites: ["tesuji_bishop_suji-chigai_l1"],
  },
  {
    id: "tesuji_bishop_kobo-kaku_l1",
    title: "攻防の角（Lv1）",
    description: "攻防の角（Lv1）。",
    category: "basics",
    status: "available",
    order: 27,
    href: "/training/tesuji/bishop/kobo-kaku",
    stars: 0,
    prerequisites: ["tesuji_bishop_kaku-kei_l1"],
  },

  // rook
  {
    id: "tesuji_rook_juji-hisha_l1",
    title: "十字飛車（Lv1）",
    description: "十字飛車（Lv1）。",
    category: "basics",
    status: "available",
    order: 28,
    href: "/training/tesuji/rook/juji-hisha",
    stars: 0,
    prerequisites: ["tesuji_bishop_kobo-kaku_l1"],
  },
  {
    id: "tesuji_rook_home-rook-drop_l1",
    title: "自陣への飛車打ち（Lv1）",
    description: "自陣への飛車打ち（Lv1）。",
    category: "basics",
    status: "available",
    order: 29,
    href: "/training/tesuji/rook/home-rook-drop",
    stars: 0,
    prerequisites: ["tesuji_rook_juji-hisha_l1"],
  },
  {
    id: "tesuji_rook_ikken-ryu_l1",
    title: "一間龍（Lv1）",
    description: "一間龍（Lv1）。",
    category: "basics",
    status: "available",
    order: 30,
    href: "/training/tesuji/rook/ikken-ryu",
    stars: 0,
    prerequisites: ["tesuji_rook_home-rook-drop_l1"],
  },
  {
    id: "tesuji_rook_okuri_l1",
    title: "送りの手筋（Lv1）",
    description: "送りの手筋（Lv1）。",
    category: "basics",
    status: "available",
    order: 31,
    href: "/training/tesuji/rook/okuri",
    stars: 0,
    prerequisites: ["tesuji_rook_ikken-ryu_l1"],
  },

  // --- 囲い（castle）Lv1（基本） ---
  {
    id: "castle_yagura_l1",
    title: "矢倉（囲い Lv1）",
    description: "金銀を寄せて守りの形を作る入口。",
    category: "basics",
    status: "available",
    order: 32,
    href: "/training/castle/yagura",
    stars: 0,
    prerequisites: ["tesuji_rook_okuri_l1"],
  },
  {
    id: "castle_funagakoi_l1",
    title: "舟囲い（囲い Lv1）",
    description: "守りの基本形を作る練習。",
    category: "basics",
    status: "available",
    order: 33,
    href: "/training/castle/funagakoi",
    stars: 0,
    prerequisites: ["castle_yagura_l1"],
  },
  {
    id: "castle_mino_l1",
    title: "美濃囲い（囲い Lv1）",
    description: "守りの形を作る練習（Lv1）。",
    category: "basics",
    status: "available",
    order: 34,
    href: "/training/castle/mino",
    stars: 0,
    prerequisites: ["castle_funagakoi_l1"],
  },
  {
    id: "castle_hidari_mino_l1",
    title: "左美濃（囲い Lv1）",
    description: "形を変えて守る感覚を掴む（Lv1）。",
    category: "basics",
    status: "available",
    order: 35,
    href: "/training/castle/hidari-mino",
    stars: 0,
    prerequisites: ["castle_mino_l1"],
  },
  {
    id: "castle_anaguma_l1",
    title: "穴熊（囲い Lv1）",
    description: "玉を奥へ寄せる“発想”の入口（Lv1）。",
    category: "basics",
    status: "available",
    order: 36,
    href: "/training/castle/anaguma",
    stars: 0,
    prerequisites: ["castle_hidari_mino_l1"],
  },
  {
    id: "castle_kinmusou_l1",
    title: "金無双（囲い Lv1）",
    description: "金の位置関係を覚える（Lv1）。",
    category: "basics",
    status: "available",
    order: 37,
    href: "/training/castle/kinmusou",
    stars: 0,
    prerequisites: ["castle_anaguma_l1"],
  },
  {
    id: "castle_nakazumai_l1",
    title: "中住まい（囲い Lv1）",
    description: "中央で守る形の入口（Lv1）。",
    category: "basics",
    status: "available",
    order: 38,
    href: "/training/castle/nakazumai",
    stars: 0,
    prerequisites: ["castle_kinmusou_l1"],
  },

  // --- 戦法（opening）Lv1（基本） ---
  {
    id: "opening_yagura_opening_l1",
    title: "矢倉（戦法 Lv1）",
    description: "歩を進め、角道・ラインを意識する入口。",
    category: "basics",
    status: "available",
    order: 39,
    href: "/training/opening/yagura-opening",
    stars: 0,
    prerequisites: ["castle_nakazumai_l1"],
  },
  {
    id: "opening_kaku_gawari_l1",
    title: "角換わり（戦法 Lv1）",
    description: "序盤の“形”を練習（Lv1）。",
    category: "basics",
    status: "available",
    order: 40,
    href: "/training/opening/kaku-gawari",
    stars: 0,
    prerequisites: ["opening_yagura_opening_l1"],
  },
  {
    id: "opening_yokofudori_l1",
    title: "横歩取り（戦法 Lv1）",
    description: "ラインの意識を育てる（Lv1）。",
    category: "basics",
    status: "available",
    order: 41,
    href: "/training/opening/yokofudori",
    stars: 0,
    prerequisites: ["opening_kaku_gawari_l1"],
  },
  {
    id: "opening_aigakari_l1",
    title: "相掛かり（戦法 Lv1）",
    description: "歩を進めて形を作る練習（Lv1）。",
    category: "basics",
    status: "available",
    order: 42,
    href: "/training/opening/aigakari",
    stars: 0,
    prerequisites: ["opening_yokofudori_l1"],
  },
  {
    id: "opening_shikenbisha_l1",
    title: "四間飛車（戦法 Lv1）",
    description: "飛車を横に動かす“振る”入口（Lv1）。",
    category: "basics",
    status: "available",
    order: 43,
    href: "/training/opening/shikenbisha",
    stars: 0,
    prerequisites: ["opening_aigakari_l1"],
  },
  {
    id: "opening_sankenbisha_l1",
    title: "三間飛車（戦法 Lv1）",
    description: "飛車の位置で作る形（Lv1）。",
    category: "basics",
    status: "available",
    order: 44,
    href: "/training/opening/sankenbisha",
    stars: 0,
    prerequisites: ["opening_shikenbisha_l1"],
  },
  {
    id: "opening_mukai_bisha_l1",
    title: "向かい飛車（戦法 Lv1）",
    description: "飛車の横移動で形を作る（Lv1）。",
    category: "basics",
    status: "available",
    order: 45,
    href: "/training/opening/mukai-bisha",
    stars: 0,
    prerequisites: ["opening_sankenbisha_l1"],
  },
  {
    id: "opening_nakabisha_l1",
    title: "中飛車（戦法 Lv1）",
    description: "中央へ飛車を振る入口（Lv1）。",
    category: "basics",
    status: "available",
    order: 46,
    href: "/training/opening/nakabisha",
    stars: 0,
    prerequisites: ["opening_mukai_bisha_l1"],
  },

];